import type { User, Team, Task, Approval } from "@/types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "harshith@hero.team",
    name: "Harshith",
    role: "TEAM_LEADER",
    teamId: "team-hero",
    avatar: "/avatars/harshith.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-2",
    email: "surmai@hero.team",
    name: "Surmai",
    role: "TEAM_MEMBER",
    teamId: "team-hero",
    avatar: "/avatars/surmai.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-3",
    email: "mano@hero.team",
    name: "Mano",
    role: "TEAM_MEMBER",
    teamId: "team-hero",
    avatar: "/avatars/mano.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-4",
    email: "latisha@hero.team",
    name: "Latisha",
    role: "TEAM_MEMBER",
    teamId: "team-hero",
    avatar: "/avatars/latisha.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-5",
    email: "shreya@boss.team",
    name: "Shreya",
    role: "TEAM_LEADER",
    teamId: "team-boss",
    avatar: "/avatars/shreya.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-6",
    email: "noel@boss.team",
    name: "Noel",
    role: "TEAM_MEMBER",
    teamId: "team-boss",
    avatar: "/avatars/noel.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-7",
    email: "rahul@boss.team",
    name: "Rahul",
    role: "TEAM_MEMBER",
    teamId: "team-boss",
    avatar: "/avatars/rahul.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "user-8",
    email: "vaibhav@boss.team",
    name: "Vaibhav",
    role: "TEAM_MEMBER",
    teamId: "team-boss",
    avatar: "/avatars/vaibhav.jpg",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "admin-1",
    email: "admin@taskflow.io",
    name: "Admin User",
    role: "ADMIN",
    teamId: "admin",
    avatar: "/avatars/admin.jpg",
    createdAt: new Date("2024-01-01"),
  },
]

export const mockTeams: Team[] = [
  {
    id: "team-hero",
    name: "HERO",
    description: "Application Development Team",
    members: mockUsers.filter((u) => u.teamId === "team-hero"),
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "team-boss",
    name: "BOSS",
    description: "Web Development & SEO Team",
    members: mockUsers.filter((u) => u.teamId === "team-boss"),
    createdAt: new Date("2024-01-01"),
  },
]

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Design Dashboard UI",
    description: "Create mockups and design system for main dashboard",
    status: "ASSIGNED",
    priority: "HIGH",
    assignedTo: "user-2",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 16,
    tags: ["design", "ui", "dashboard"],
    scheduledTime: new Date("2024-10-20"),
    dueDate: new Date("2024-10-25"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-2",
    title: "Setup Database Schema",
    description: "Create PostgreSQL schema for tasks and approvals",
    status: "IN_PROGRESS",
    priority: "URGENT",
    assignedTo: "user-3",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 8,
    actualHours: 4,
    tags: ["backend", "database"],
    scheduledTime: new Date("2024-10-18"),
    dueDate: new Date("2024-10-22"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-3",
    title: "AWS Infrastructure Setup",
    description: "Configure EC2, RDS, and S3 for production",
    status: "PENDING_APPROVAL",
    priority: "HIGH",
    assignedTo: "user-4",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 12,
    tags: ["aws", "infrastructure", "devops"],
    scheduledTime: new Date("2024-10-19"),
    dueDate: new Date("2024-10-28"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-4",
    title: "API Authentication Implementation",
    description: "Implement JWT-based authentication for REST API",
    status: "IN_PROGRESS",
    priority: "HIGH",
    assignedTo: "user-3",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 10,
    actualHours: 6,
    tags: ["backend", "security", "api"],
    scheduledTime: new Date("2024-10-21"),
    dueDate: new Date("2024-10-26"),
    createdAt: new Date("2024-10-16"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-5",
    title: "Frontend Component Library",
    description: "Build reusable React component library with Storybook",
    status: "ASSIGNED",
    priority: "MEDIUM",
    assignedTo: "user-2",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 20,
    tags: ["frontend", "components", "react"],
    scheduledTime: new Date("2024-10-22"),
    dueDate: new Date("2024-11-05"),
    createdAt: new Date("2024-10-15"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-6",
    title: "Website SEO Optimization",
    description: "Optimize website for search engines and improve rankings",
    status: "COMPLETED",
    priority: "MEDIUM",
    assignedTo: "user-6",
    createdBy: "user-5",
    teamId: "team-boss",
    estimatedHours: 15,
    actualHours: 14,
    tags: ["seo", "marketing", "optimization"],
    scheduledTime: new Date("2024-10-10"),
    dueDate: new Date("2024-10-17"),
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-7",
    title: "Mobile App Responsive Design",
    description: "Ensure all pages are responsive on mobile devices",
    status: "IN_PROGRESS",
    priority: "HIGH",
    assignedTo: "user-7",
    createdBy: "user-5",
    teamId: "team-boss",
    estimatedHours: 18,
    actualHours: 8,
    tags: ["frontend", "mobile", "responsive"],
    scheduledTime: new Date("2024-10-19"),
    dueDate: new Date("2024-10-29"),
    createdAt: new Date("2024-10-14"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-8",
    title: "Performance Testing & Optimization",
    description: "Run performance tests and optimize slow endpoints",
    status: "PENDING_APPROVAL",
    priority: "MEDIUM",
    assignedTo: "user-8",
    createdBy: "user-5",
    teamId: "team-boss",
    estimatedHours: 12,
    tags: ["testing", "performance", "optimization"],
    scheduledTime: new Date("2024-10-20"),
    dueDate: new Date("2024-10-27"),
    createdAt: new Date("2024-10-16"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-9",
    title: "Documentation & API Docs",
    description: "Write comprehensive API documentation and user guides",
    status: "DRAFT",
    priority: "LOW",
    assignedTo: "user-4",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 8,
    tags: ["documentation", "api"],
    scheduledTime: new Date("2024-10-25"),
    dueDate: new Date("2024-11-01"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-10",
    title: "User Testing & Feedback Collection",
    description: "Conduct user testing sessions and collect feedback",
    status: "ASSIGNED",
    priority: "MEDIUM",
    assignedTo: "user-6",
    createdBy: "user-5",
    teamId: "team-boss",
    estimatedHours: 10,
    tags: ["testing", "ux", "feedback"],
    scheduledTime: new Date("2024-10-23"),
    dueDate: new Date("2024-10-30"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-11",
    title: "Email Notification System",
    description: "Implement email notifications for task updates and approvals",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    assignedTo: "user-3",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 9,
    actualHours: 3,
    tags: ["backend", "notifications", "email"],
    scheduledTime: new Date("2024-10-21"),
    dueDate: new Date("2024-10-28"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "task-12",
    title: "Analytics Dashboard Implementation",
    description: "Build analytics dashboard with charts and metrics",
    status: "ASSIGNED",
    priority: "HIGH",
    assignedTo: "user-2",
    createdBy: "user-1",
    teamId: "team-hero",
    estimatedHours: 14,
    tags: ["frontend", "analytics", "dashboard"],
    scheduledTime: new Date("2024-10-24"),
    dueDate: new Date("2024-11-02"),
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
]

export const mockApprovals: Approval[] = [
  {
    id: "approval-1",
    taskId: "task-3",
    status: "PENDING",
    requestedBy: "user-1",
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "approval-2",
    taskId: "task-8",
    status: "PENDING",
    requestedBy: "user-5",
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "approval-3",
    taskId: "task-1",
    status: "APPROVED",
    requestedBy: "user-1",
    approvedBy: "user-5",
    createdAt: new Date("2024-10-16"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "approval-4",
    taskId: "task-2",
    status: "APPROVED",
    requestedBy: "user-1",
    approvedBy: "user-5",
    createdAt: new Date("2024-10-15"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "approval-5",
    taskId: "task-6",
    status: "APPROVED",
    requestedBy: "user-5",
    approvedBy: "user-1",
    createdAt: new Date("2024-10-10"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "approval-6",
    taskId: "task-7",
    status: "REJECTED",
    requestedBy: "user-5",
    approvedBy: "user-1",
    createdAt: new Date("2024-10-14"),
    updatedAt: new Date("2024-10-17"),
  },
  {
    id: "approval-7",
    taskId: "task-4",
    status: "ESCALATED",
    requestedBy: "user-1",
    createdAt: new Date("2024-10-17"),
    updatedAt: new Date("2024-10-17"),
  },
]
